services:
  saarthi-app:
    container_name: saarthi-app
    build:
      context: .
      dockerfile: Dockerfile
    image: adhirajpandey/saarthi:latest
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
